### ISSUE TITLE
Unload method has NRE exception when another mod has an error at main loading

### ISSUE THREAD

**Issue by z3nth10n** [DRKV333/ShopExpander#1]
This method has an NRE, I don't know where because the DLL was built on Release mode. But this error enforces tModLoader to exit Terraria, making large modpack loading (debugging it) slow.

https://github.com/DRKV333/ShopExpander/blob/master/ShopExpander/ShopExpander.cs#L68

**Comment by DRKV333** [comment]
Wait, you mean `Patches.SetupShopPatch.Unload()` in particular? I don't really think there is anything there that could throw a null reference exception...

This line could be causing problems if the mod gets unloaded before fully loading. I guess that could be it. https://github.com/DRKV333/ShopExpander/blob/185c657f78851b5687538048b371b597aa79c354/ShopExpander/ShopExpander.cs#L69

It could also be something from inside Harmony. It can do some weird things sometimes. 

I mean, even if the dll was optimized, you should still be able to get a stack trace for this, or something. That would be helpful.

**Comment by z3nth10n** [comment]
> This line could be causing problems if the mod gets unloaded before fully loading. I guess that could be it.

Yep, this is what I mean.

> I mean, even if the dll was optimized, you should still be able to get a stack trace for this, or something. That would be helpful.

Well... The exact line isn't visible, the exception is coming from here. Just try to do it Nullable, some like `harmonyInstance?.UnpatchAll()` should be fine. Is obvious that you're trying to call a method from an instance of an object that hasn't been set yet due to an exception caused from another mod.

**Comment by DRKV333** [comment]
Yeah, this should fix it. :)

I can't use null conditional operators unfortunately, because tModLoader doesn't really work too well with C# 6 currently.
